# Generated by Django 5.2.6 on 2025-09-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField()),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
